name: jaeger-flask-test

replicaCount: 1
workerReplicaCount: 1

restartPolicy: Always

image:
  flaskApp: jaeger-flask-test:0.0.1

deployment:
  flaskApp:
    containerPort: 5000
    flaskConfig: "local_k8s"

service:
  flaskApp:
    type: LoadBalancer
    port: 8081
    targetPort: 5000

smtp:
  server: "mail.int.8451.com"
  fromAddr: "local-no-reply@8451.com"
  toAddr: "david.scroggins.contractor@8451.com"

postgresql:
  postgresDatabase: airflow
  dbUsername: airflow
  dbPassword: airflow

airmondb:
  url: postgresql://airmon:airmon@airmon-postgres:5433/airmon

redis:
  redisUrl: "redis://:admin123@redis:6379/0"

airflow:
  webserverUrl: "http://webserver:8080/admin"
